### ISSUE TITLE
Help appreciated

### ISSUE THREAD

**Issue by Stan-imr** [project-asap/workflow#1]
Hello,

Trying to install ASAP, we first target the WMT component. A nginx server has been set up in a Linux machine, with php-fm and python as required. The WMT code has been downloaded, we changed the conf file and move it to the /etc/nginx/sites-enabled.

Now when we access the app with a browser, a 403 HTTP issue is raised. It turns out that the server looks for some index.html file which does not exist.

[error] 13#13: *1 directory index of "/home/workflow/pub/" is forbidden,
 
We created a symlink index.html that points to main.html. That solved the issue, but the package should be corrected IMO. 

Still investigating. Thanks.

**Comment by maxfil** [comment]
Documentation for nginx configuration is refined
