### ISSUE TITLE
Any future release of this tool?

### ISSUE THREAD

**Issue by rigaux** [project-asap/workflow#2]
Hello,

We definitely need an upgrade of this tool to use it. Upgrade should include (i) an improved documentation, explaining in detail the definition of datasets, operators and workflows and how they relate to the equivalent concepts in IRES, (ii) a running connection with IRES and (iii) improvement of ergonomic features (controls of consistency for instance: seems that we can do anything now) and user friendliness. Please keep us informed of any new release. Thanks!

Philippe

**Comment by maxfil** [comment]
Integration with IRES improved, interface has been updated (tabs were added and so on) in commit c1962079873e5ad06821e6f412d3e8ba490c28ca
